//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CVler
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Ata_adi { get; set; }
        public int CinsId { get; set; }
        public int Min_yashId { get; set; }
        public string Shekil { get; set; }
        public int TehsilId { get; set; }
        public int Ish_tecrubesiId { get; set; }
        public int VezifeId { get; set; }
        public int SheherId { get; set; }
        public int Min_maashId { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public string Elave_melumat { get; set; }
        public int KategoriyaId { get; set; }
        public System.DateTime Cvnin_tarixi { get; set; }
        public Nullable<System.DateTime> Bitme_tarixi { get; set; }
        public bool Status { get; set; }
    
        public virtual Cinsler Cinsler { get; set; }
        public virtual Ish_tecrubesi Ish_tecrubesi { get; set; }
        public virtual Kategoriya Kategoriya { get; set; }
        public virtual Min_maash Min_maash { get; set; }
        public virtual Min_yashlar Min_yashlar { get; set; }
        public virtual Sheher Sheher { get; set; }
        public virtual Tehsil Tehsil { get; set; }
        public virtual Vezife Vezife { get; set; }
    }
}
