//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFinal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class isaxtarEntities : DbContext
    {
        public isaxtarEntities()
            : base("name=isaxtarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Blog> Blog { get; set; }
        public virtual DbSet<Cinsler> Cinsler { get; set; }
        public virtual DbSet<CVler> CVler { get; set; }
        public virtual DbSet<Elanlar> Elanlar { get; set; }
        public virtual DbSet<Haqqimizda> Haqqimizda { get; set; }
        public virtual DbSet<Ish_tecrubesi> Ish_tecrubesi { get; set; }
        public virtual DbSet<Istifadeci> Istifadeci { get; set; }
        public virtual DbSet<Kategoriya> Kategoriya { get; set; }
        public virtual DbSet<Max_maash> Max_maash { get; set; }
        public virtual DbSet<Max_yashlar> Max_yashlar { get; set; }
        public virtual DbSet<Min_maash> Min_maash { get; set; }
        public virtual DbSet<Min_yashlar> Min_yashlar { get; set; }
        public virtual DbSet<Sheher> Sheher { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tehsil> Tehsil { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Vezife> Vezife { get; set; }
    }
}
