//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elanlar
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public int VezifeId { get; set; }
        public string Shirket_adi { get; set; }
        public int Min_maashId { get; set; }
        public int Max_maashId { get; set; }
        public int SheherId { get; set; }
        public int Min_yashId { get; set; }
        public int Max_yashId { get; set; }
        public int TehsilId { get; set; }
        public int Ish_tecrubesiId { get; set; }
        public System.DateTime Elanin_tarixi { get; set; }
        public Nullable<System.DateTime> Bitme_tarixi { get; set; }
        public string Elaqedar_shexs { get; set; }
        public string Ish_barede_melumat { get; set; }
        public string Namizede_telebler { get; set; }
        public int KategoriyaId { get; set; }
        public bool Status { get; set; }
    
        public virtual Ish_tecrubesi Ish_tecrubesi { get; set; }
        public virtual Kategoriya Kategoriya { get; set; }
        public virtual Max_maash Max_maash { get; set; }
        public virtual Max_yashlar Max_yashlar { get; set; }
        public virtual Min_maash Min_maash { get; set; }
        public virtual Min_yashlar Min_yashlar { get; set; }
        public virtual Sheher Sheher { get; set; }
        public virtual Tehsil Tehsil { get; set; }
        public virtual Vezife Vezife { get; set; }
    }
}
